services:
    clickpress_newspodcasts.listener.generate_page:
        class: Clickpress\NewsPodcasts\EventListener\GeneratePageListener
        arguments:
        - '@contao.framework'
        tags:
        - { name: contao.hook, hook: generatePage }
        public: true
