services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Clickpress\NewsPodcasts\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection}

    clickpress_newspodcasts.listener.generatexml:
        class: Clickpress\NewsPodcasts\EventListener\GenerateXmlFilesListener
        tags: [ 'terminal42_service_annotation' ]

    clickpress_newspodcasts.listener.removeoldfeeds:
        class: Clickpress\NewsPodcasts\EventListener\RemoveOldFeedsListener
        tags: [ 'terminal42_service_annotation' ]

    Clickpress\NewsPodcasts\Helper\GetMp3Duration:
      arguments:
        $filename: ""

    Clickpress\NewsPodcasts\Helper\PodcastFeedHelper:
      arguments:
        $strName: ""
